INSERT INTO tablas_referencia (id, nombre, descripcion)
VALUES
(1, 'acciones', 'Catálogo de acciones ejecutables y auditables dentro del sistema'),
(2, 'acciones_tipo', 'Tipos transaccionales de acciones del sistema'),
(3, 'ciudades', 'Catálogo de ciudades'),
(4, 'cliente_contrapartes', 'Contrapartes asociadas a clientes'),
(5, 'clientes', 'Clientes registrados en el sistema'),
(6, 'comunas', 'Catálogo de comunas'),
(7, 'cumplimiento_documento_versiones', 'Versiones de documentos de cumplimiento y capacitaciones'),
(8, 'cumplimiento_documentos', 'Documentos maestros de cumplimiento y capacitaciones'),
(9, 'cumplimiento_lecturas', 'Registro de lecturas y aceptaciones de cumplimiento por usuario'),
(10, 'cumplimiento_pregunta_alternativas', 'Alternativas de respuestas para preguntas de cumplimiento'),
(11, 'cumplimiento_preguntas', 'Preguntas asociadas a evaluaciones de cumplimiento'),
(12, 'direcciones', 'Direcciones físicas asociadas a entidades del sistema'),
(13, 'espacios', 'Espacios físicos o áreas operacionales'),
(14, 'estado_tipos', 'Catálogo de estados genéricos utilizados en el sistema'),
(15, 'grupo_tipos', 'Grupo tipo de usuario en proyectos, ejemplo: Admins grupo tipo de Administradores'),
(16, 'historial_tareas', 'Historial de cambios y eventos asociados a tareas'),
(17, 'menu', 'Opciones de menú disponibles en el sistema'),
(18, 'menu_grupo', 'Agrupadores de menús del sistema'),
(19, 'notificacion_medios', 'Medios disponibles para envío de notificaciones'),
(20, 'notificacion_tipos', 'Tipos de notificaciones del sistema'),
(21, 'paises', 'Catálogo de países'),
(22, 'permiso_tipos', 'Tipos de permisos disponibles para perfiles de usuario'),
(23, 'personas', 'Personas registradas en el sistema'),
(24, 'proveedor_proceso_tareas', 'Tareas de un proceso creado en un proveedor'),
(25, 'proveedor_procesos', 'Procesos asociados a proveedores'),
(26, 'proveedores', 'Proveedores registrados en el sistema'),
(27, 'provincia', 'Catálogo de provincias'),
(28, 'proyecto_feriados', 'Feriados asociados a proyectos'),
(29, 'proyecto_tareas', 'Relación entre proyectos y tareas'),
(30, 'proyecto_usuarios_grupo', 'Agrupación de usuarios asociados a proyectos'),
(31, 'proyecto_usuarios_grupo_disponibilidad', 'Disponibilidad de usuarios en grupos de proyecto'),
(32, 'proyectos', 'Proyectos registrados en el sistema'),
(33, 'regiones', 'Catálogo de regiones'),
(34, 'tablas_referencia', 'Catálogo de tablas en SETAP'),
(35, 'tarea_categorias', 'Categorías de tareas'),
(36, 'tarea_fotos', 'Fotografías y evidencias asociadas a tareas'),
(37, 'tarea_tipos', 'Tipos de tareas disponibles'),
(38, 'tareas', 'Tareas operacionales del sistema'),
(39, 'tipos_espacio', 'Tipos de espacios físicos'),
(40, 'tipos_fecha', 'Tipo de fecha segun condicion legal laboral: licencia, vacacion'),
(41, 'usuario_logs', 'Bitácora de acciones ejecutadas por usuarios'),
(42, 'usuario_notificaciones', 'Notificaciones asociadas a usuarios'),
(43, 'usuario_tipo_menus', 'Relación entre perfiles de usuario y menús'),
(44, 'usuario_tipo_permisos', 'Relación entre perfiles de usuario y permisos'),
(45, 'usuario_tipos', 'Perfiles o tipos de usuario'),
(46, 'usuarios', 'Usuarios autenticables del sistema');