INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '1', 'login', 1;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '2', 'logout', 2;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '3', 'Creo usuario', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '4', 'Modifico Usuario', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '5', 'Elimino Usuario', 5; 
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '6', 'Crea tarea tipo en proyecto', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '7', 'Crea proyecto-tarea masivo', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '8', 'Crea proyecto-tarea especifica', 3; 
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '9', 'Crea proyecto-tarea rango', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '10', 'Crea proyecto-tarea intervalo', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '11', 'Crea tarea tipo', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '12', 'Actualiza proyecto-tarea', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '13', 'Eliminación masiva proyecto-tarea', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '14', 'Eliminación de proyecto-tarea', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '15', 'Eliminación tarea tipo', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '16', 'Cambio estado de tarea', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '17', 'Carga foto de evidencia', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '18', 'Cambio estado grupo tareas', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '19', 'Crea cliente', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '20', 'Modifica Cliente', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '21', 'Elimina cliente', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '22', 'Crea contraparte', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '23', 'Modifica contraparte', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '24', 'Elimina contraparte', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '25', 'Crea dirección', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '26', 'Modifica espacio', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '27', 'Crea espacio', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '29', 'Elimina espacio', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '30', 'Crea grupo tipo', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '31', 'Edita grupo tipo', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '32', 'Crea menú', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '33', 'Modifica menú', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '34', 'Elimina menú', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '35', 'Actualiza perfil', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '36', 'Cambia contraseña', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '37', 'Actualiza permisos', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '38', 'Crea persona', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '39', 'Modifica de persona', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '40', 'Elimina persona', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '41', 'Crea proceso', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '42', 'Modifica proceso', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '43', 'Elimina proceso', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '44', 'Crea de proyecto', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '45', 'Actualiza proyecto', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '46', 'Elimina proyecto', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '47', 'Cambia estado proyecto', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '48', 'Agrega usuario a grupo', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '49', 'Actualiza usuario grupo', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '50', 'Elimina usuario grupo', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '51', 'Agrega ejecutor', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '52', 'Guarda calendario', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '53', 'Elimina calendario', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '54', 'Agrega fecha calendario colaborador', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '55', 'Modifica fecha calendario colaborador', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '56', 'Crea feriados masivamente', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '57', 'Crea feriado fecha específica', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '58', 'Crea feriados rango', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '59', 'Edita feriado', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '60', 'Elimina feriado', 5;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '61', 'Mueve tareas por feriado', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '62', 'Crea proveedor', 3;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '63', 'Edita proveedor', 4;
INSERT INTO acciones (id, nombre, acciones_tipo_id) Select '64', 'Elimina proveedor', 5;