CREATE TABLE cumplimiento_documento_versiones (
  id int NOT NULL AUTO_INCREMENT,
  cumplimiento_documento_id int NOT NULL,
  version varchar(50) NOT NULL,
  titulo varchar(250) NOT NULL,
  resumen varchar(1000) DEFAULT NULL,
  contenido_html longtext NOT NULL,
  hash_documento varchar(255) DEFAULT NULL,
  publicado tinyint NOT NULL DEFAULT '0',
  fecha_publicacion datetime DEFAULT NULL,
  fecha_inicio_vigencia date DEFAULT NULL,
  fecha_fin_vigencia date DEFAULT NULL,
  creado_por_usuario_id int DEFAULT NULL,
  fecha_creacion timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_modificacion timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  proveedor_id int DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_documento_version (cumplimiento_documento_id,version),
  KEY idx_documento_version_publicado (publicado),
  KEY fk_doc_version_usuario (creado_por_usuario_id),
  KEY fk_proveedor_id_idx (proveedor_id),
  CONSTRAINT fk_doc_version_documento FOREIGN KEY (cumplimiento_documento_id) REFERENCES cumplimiento_documentos (id),
  CONSTRAINT fk_doc_version_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (id),
  CONSTRAINT fk_doc_version_usuario FOREIGN KEY (creado_por_usuario_id) REFERENCES usuarios (id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE cumplimiento_documentos (
  id int NOT NULL AUTO_INCREMENT,
  proveedor_id int NOT NULL,
  nombre varchar(250) NOT NULL,
  codigo varchar(100) DEFAULT NULL,
  descripcion varchar(500) DEFAULT NULL,
  requiere_evaluacion tinyint NOT NULL DEFAULT '1',
  puntaje_minimo decimal(5,2) NOT NULL DEFAULT '80.00',
  cantidad_preguntas int NOT NULL DEFAULT '5',
  vigencia_dias int NOT NULL DEFAULT '365',
  estado_tipo_id int NOT NULL DEFAULT '1',
  fecha_creacion timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_modificacion timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_documento_proveedor (proveedor_id),
  KEY idx_documento_estado (estado_tipo_id),
  CONSTRAINT fk_documento_estado FOREIGN KEY (estado_tipo_id) REFERENCES estado_tipos (id),
  CONSTRAINT fk_documento_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE cumplimiento_lecturas (
  id int NOT NULL AUTO_INCREMENT,
  usuario_id int NOT NULL,
  cumplimiento_documento_version_id int NOT NULL,
  fecha_inicio_lectura datetime DEFAULT NULL,
  fecha_fin_lectura datetime DEFAULT NULL,
  fecha_aceptacion datetime DEFAULT NULL,
  password_confirmado tinyint NOT NULL DEFAULT '0',
  puntaje_obtenido decimal(5,2) DEFAULT NULL,
  aprobado tinyint NOT NULL DEFAULT '0',
  fecha_vencimiento date DEFAULT NULL,
  codigo_certificado varchar(100) DEFAULT NULL,
  certificado_generado tinyint NOT NULL DEFAULT '0',
  ip varchar(45) DEFAULT NULL,
  user_agent varchar(500) DEFAULT NULL,
  observaciones varchar(1000) DEFAULT NULL,
  fecha_creacion timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_modificacion timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  proveedor_id int DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_lecturas_usuario (usuario_id),
  KEY idx_lecturas_version (cumplimiento_documento_version_id),
  KEY idx_lecturas_vencimiento (fecha_vencimiento),
  KEY fk_lectura_proveedor_id_idx (proveedor_id),
  CONSTRAINT fk_lectura_proveedor_id FOREIGN KEY (proveedor_id) REFERENCES proveedores (id),
  CONSTRAINT fk_lectura_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
  CONSTRAINT fk_lectura_version FOREIGN KEY (cumplimiento_documento_version_id) REFERENCES cumplimiento_documento_versiones (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE cumplimiento_pregunta_alternativas (
  id int NOT NULL AUTO_INCREMENT,
  cumplimiento_pregunta_id int NOT NULL,
  alternativa varchar(1000) NOT NULL,
  es_correcta tinyint NOT NULL DEFAULT '0',
  orden_visualizacion int NOT NULL DEFAULT '1',
  proveedor_id int DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_alternativas_pregunta (cumplimiento_pregunta_id),
  KEY fk_alternativa_pregunta_proveedor_id_idx (proveedor_id),
  CONSTRAINT fk_alternativa_pregunta_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (id),
  CONSTRAINT fk_alternativas_pregunta FOREIGN KEY (cumplimiento_pregunta_id) REFERENCES cumplimiento_preguntas (id)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE cumplimiento_preguntas (
  id int NOT NULL AUTO_INCREMENT,
  cumplimiento_documento_version_id int NOT NULL,
  pregunta varchar(1000) NOT NULL,
  orden_visualizacion int NOT NULL DEFAULT '1',
  estado_tipo_id int NOT NULL DEFAULT '1',
  fecha_creacion timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  proveedor_id int DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_preguntas_version (cumplimiento_documento_version_id),
  KEY fk_preguntas_estado (estado_tipo_id),
  KEY fk_preguntas_proveedor_id_idx (proveedor_id),
  CONSTRAINT fk_preguntas_estado FOREIGN KEY (estado_tipo_id) REFERENCES estado_tipos (id),
  CONSTRAINT fk_preguntas_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (id),
  CONSTRAINT fk_preguntas_version FOREIGN KEY (cumplimiento_documento_version_id) REFERENCES cumplimiento_documento_versiones (id)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE cumplimiento_respuestas_usuario (
  id int NOT NULL AUTO_INCREMENT,
  cumplimiento_lectura_id int NOT NULL,
  cumplimiento_pregunta_id int NOT NULL,
  cumplimiento_pregunta_alternativa_id int NOT NULL,
  correcta tinyint NOT NULL DEFAULT '0',
  fecha_creacion timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  proveedor_id int DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_respuestas_lectura (cumplimiento_lectura_id),
  KEY fk_respuesta_pregunta (cumplimiento_pregunta_id),
  KEY fk_respuesta_alternativa (cumplimiento_pregunta_alternativa_id),
  KEY fk_respuestas_usuario_proveedor_id_idx (proveedor_id),
  CONSTRAINT fk_respuesta_alternativa FOREIGN KEY (cumplimiento_pregunta_alternativa_id) REFERENCES cumplimiento_pregunta_alternativas (id),
  CONSTRAINT fk_respuesta_lectura FOREIGN KEY (cumplimiento_lectura_id) REFERENCES cumplimiento_lecturas (id),
  CONSTRAINT fk_respuesta_pregunta FOREIGN KEY (cumplimiento_pregunta_id) REFERENCES cumplimiento_preguntas (id),
  CONSTRAINT fk_respuestas_usuario_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
